package e.c.a.g.a.f.e;

import com.kugou.common.config.ConfigKey;

/* JADX INFO: loaded from: classes.dex */
public interface b {
    public static final ConfigKey A;
    public static final ConfigKey A0;
    public static final ConfigKey A1;
    public static final ConfigKey A2;
    public static final ConfigKey A3;
    public static final ConfigKey B;
    public static final ConfigKey B0;
    public static final ConfigKey B1;
    public static final ConfigKey B2;
    public static final ConfigKey B3;
    public static final ConfigKey C;
    public static final ConfigKey C0;
    public static final ConfigKey C1;
    public static final ConfigKey C2;
    public static final ConfigKey C3;
    public static final ConfigKey D;
    public static final ConfigKey D0;
    public static final ConfigKey D1;
    public static final ConfigKey D2;
    public static final ConfigKey D3;
    public static final ConfigKey E;
    public static final ConfigKey E0;
    public static final ConfigKey E1;
    public static final ConfigKey E2;
    public static final ConfigKey E3;
    public static final ConfigKey F;
    public static final ConfigKey F0;
    public static final ConfigKey F1;
    public static final ConfigKey F2;
    public static final ConfigKey F3;
    public static final ConfigKey G;
    public static final ConfigKey G0;
    public static final ConfigKey G1;
    public static final ConfigKey G2;
    public static final ConfigKey G3;
    public static final ConfigKey H;
    public static final ConfigKey H0;
    public static final ConfigKey H1;
    public static final ConfigKey H2;
    public static final ConfigKey H3;
    public static final ConfigKey I;
    public static final ConfigKey I0;
    public static final ConfigKey I1;
    public static final ConfigKey I2;
    public static final ConfigKey I3;
    public static final ConfigKey J;
    public static final ConfigKey J0;
    public static final ConfigKey J1;
    public static final ConfigKey J2;
    public static final ConfigKey J3;
    public static final ConfigKey K;
    public static final ConfigKey K0;
    public static final ConfigKey K1;
    public static final ConfigKey K2;
    public static final ConfigKey K3;
    public static final ConfigKey L;
    public static final ConfigKey L0;
    public static final ConfigKey L1;
    public static final ConfigKey L2;
    public static final ConfigKey L3;
    public static final ConfigKey M;
    public static final ConfigKey M0;
    public static final ConfigKey M1;
    public static final ConfigKey M2;
    public static final ConfigKey M3;
    public static final ConfigKey N;
    public static final ConfigKey N0;
    public static final ConfigKey N1;
    public static final ConfigKey N2;
    public static final ConfigKey N3;
    public static final ConfigKey O;
    public static final ConfigKey O0;
    public static final ConfigKey O1;
    public static final ConfigKey O2;
    public static final ConfigKey O3;
    public static final ConfigKey P;
    public static final ConfigKey P0;
    public static final ConfigKey P1;
    public static final ConfigKey P2;
    public static final ConfigKey P3;
    public static final ConfigKey Q;
    public static final ConfigKey Q0;
    public static final ConfigKey Q1;
    public static final ConfigKey Q2;
    public static final ConfigKey Q3;
    public static final ConfigKey R;
    public static final ConfigKey R0;
    public static final ConfigKey R1;
    public static final ConfigKey R2;
    public static final ConfigKey R3;
    public static final ConfigKey S;
    public static final ConfigKey S0;
    public static final ConfigKey S1;
    public static final ConfigKey S2;
    public static final ConfigKey S3;
    public static final ConfigKey T;
    public static final ConfigKey T0;
    public static final ConfigKey T1;
    public static final ConfigKey T2;
    public static final ConfigKey T3;
    public static final ConfigKey U;
    public static final ConfigKey U0;
    public static final ConfigKey U1;
    public static final ConfigKey U2;
    public static final ConfigKey U3;
    public static final ConfigKey V;
    public static final ConfigKey V0;
    public static final ConfigKey V1;
    public static final ConfigKey V2;
    public static final ConfigKey V3;
    public static final ConfigKey W;
    public static final ConfigKey W0;
    public static final ConfigKey W1;
    public static final ConfigKey W2;
    public static final ConfigKey W3;
    public static final ConfigKey X;
    public static final ConfigKey X0;
    public static final ConfigKey X1;
    public static final ConfigKey X2;
    public static final ConfigKey X3;
    public static final ConfigKey Y;
    public static final ConfigKey Y0;
    public static final ConfigKey Y1;
    public static final ConfigKey Y2;
    public static final ConfigKey Y3;
    public static final ConfigKey Z;
    public static final ConfigKey Z0;
    public static final ConfigKey Z1;
    public static final ConfigKey Z2;
    public static final ConfigKey Z3;
    public static final ConfigKey a0;
    public static final ConfigKey a1;
    public static final ConfigKey a2;
    public static final ConfigKey a3;
    public static final ConfigKey a4;
    public static final ConfigKey b0;
    public static final ConfigKey b1;
    public static final ConfigKey b2;
    public static final ConfigKey b3;
    public static final ConfigKey b4;
    public static final ConfigKey c0;
    public static final ConfigKey c1;
    public static final ConfigKey c2;
    public static final ConfigKey c3;
    public static final ConfigKey c4;
    public static final ConfigKey d0;
    public static final ConfigKey d1;
    public static final ConfigKey d2;
    public static final ConfigKey d3;
    public static final ConfigKey d4;
    public static final ConfigKey e0;
    public static final ConfigKey e1;
    public static final ConfigKey e2;
    public static final ConfigKey e3;
    public static final ConfigKey e4;
    public static final ConfigKey f0;
    public static final ConfigKey f1;
    public static final ConfigKey f2;
    public static final ConfigKey f3;
    public static final ConfigKey f4;
    public static final ConfigKey g0;
    public static final ConfigKey g1;
    public static final ConfigKey g2;
    public static final ConfigKey g3;
    public static final ConfigKey g4;
    public static final ConfigKey h0;
    public static final ConfigKey h1;
    public static final ConfigKey h2;
    public static final ConfigKey h3;
    public static final ConfigKey h4;
    public static final ConfigKey i0;
    public static final ConfigKey i1;
    public static final ConfigKey i2;
    public static final ConfigKey i3;
    public static final ConfigKey i4;
    public static final ConfigKey j0;
    public static final ConfigKey j1;
    public static final ConfigKey j2;
    public static final ConfigKey j3;
    public static final ConfigKey j4;
    public static final ConfigKey k0;
    public static final ConfigKey k1;
    public static final ConfigKey k2;
    public static final ConfigKey k3;
    public static final ConfigKey k4;
    public static final ConfigKey l0;
    public static final ConfigKey l1;
    public static final ConfigKey l2;
    public static final ConfigKey l3;
    public static final ConfigKey l4;
    public static final ConfigKey m0;
    public static final ConfigKey m1;
    public static final ConfigKey m2;
    public static final ConfigKey m3;
    public static final ConfigKey m4;
    public static final ConfigKey n0;
    public static final ConfigKey n1;
    public static final ConfigKey n2;
    public static final ConfigKey n3;
    public static final ConfigKey n4;
    public static final ConfigKey o0;
    public static final ConfigKey o1;
    public static final ConfigKey o2;
    public static final ConfigKey o3;
    public static final ConfigKey o4;
    public static final ConfigKey p0;
    public static final ConfigKey p1;
    public static final ConfigKey p2;
    public static final ConfigKey p3;
    public static final ConfigKey p4;
    public static final ConfigKey q0;
    public static final ConfigKey q1;
    public static final ConfigKey q2;
    public static final ConfigKey q3;
    public static final ConfigKey q4;
    public static final ConfigKey r0;
    public static final ConfigKey r1;
    public static final ConfigKey r2;
    public static final ConfigKey r3;
    public static final ConfigKey r4;
    public static final ConfigKey s0;
    public static final ConfigKey s1;
    public static final ConfigKey s2;
    public static final ConfigKey s3;
    public static final ConfigKey t0;
    public static final ConfigKey t1;
    public static final ConfigKey t2;
    public static final ConfigKey t3;
    public static final ConfigKey u0;
    public static final ConfigKey u1;
    public static final ConfigKey u2;
    public static final ConfigKey u3;
    public static final ConfigKey v0;
    public static final ConfigKey v1;
    public static final ConfigKey v2;
    public static final ConfigKey v3;
    public static final ConfigKey w;
    public static final ConfigKey w0;
    public static final ConfigKey w1;
    public static final ConfigKey w2;
    public static final ConfigKey w3;
    public static final ConfigKey x;
    public static final ConfigKey x0;
    public static final ConfigKey x1;
    public static final ConfigKey x2;
    public static final ConfigKey x3;
    public static final ConfigKey y;
    public static final ConfigKey y0;
    public static final ConfigKey y1;
    public static final ConfigKey y2;
    public static final ConfigKey y3;
    public static final ConfigKey z;
    public static final ConfigKey z0;
    public static final ConfigKey z1;
    public static final ConfigKey z2;
    public static final ConfigKey z3;
    public static final ConfigKey a = new ConfigKey("listen.gateway.url.ackv2");
    public static final ConfigKey b = new ConfigKey("listen.gateway.ackdomainbackup");
    public static final ConfigKey c = new ConfigKey("listen.usersdkparam.appid");

    /* JADX INFO: renamed from: d, reason: collision with root package name */
    public static final ConfigKey f642d = new ConfigKey("listen.usersdkparam.appkey");

    /* JADX INFO: renamed from: e, reason: collision with root package name */
    public static final ConfigKey f643e = new ConfigKey("listen.storagemodule.tracker_pidversion");

    /* JADX INFO: renamed from: f, reason: collision with root package name */
    public static final ConfigKey f644f = new ConfigKey("listen.storagemodule.tracker_pidversion_sercret");

    /* JADX INFO: renamed from: g, reason: collision with root package name */
    public static final ConfigKey f645g = new ConfigKey("listen.usersdkparam.apprsa");

    /* JADX INFO: renamed from: h, reason: collision with root package name */
    public static final ConfigKey f646h = new ConfigKey("listen.usermodule.login.by_verifycode_v6");

    /* JADX INFO: renamed from: i, reason: collision with root package name */
    public static final ConfigKey f647i = new ConfigKey("young.img.open_heic_covert");
    public static final ConfigKey j = new ConfigKey("young.qa.upload_new_bucket");
    public static final ConfigKey k = new ConfigKey("ktv.common.bss.upload_v3");
    public static final ConfigKey l = new ConfigKey("young.bss.upload.feedback_img_host");
    public static final ConfigKey m = new ConfigKey("listen.usermodule.url.get_login_extend_info_v2");
    public static final ConfigKey n = new ConfigKey("listen.usermodule.login.by_token_v4");
    public static final ConfigKey o = new ConfigKey("listen.usermodule.login.by_openplat_v5");
    public static final ConfigKey p = new ConfigKey("listen.usermodule.login.by_pwd_v8");
    public static final ConfigKey q = new ConfigKey("usermodule.unionvip.get");
    public static final ConfigKey r = new ConfigKey("song.copyright.use_container_id");
    public static final ConfigKey s = new ConfigKey("listen.switchparam.enable_ui_render");
    public static final ConfigKey t = new ConfigKey("listen.configmodule.appconfig.index_https");
    public static final ConfigKey u = new ConfigKey("listen.user.qr_code_scan_wx");
    public static final ConfigKey v = new ConfigKey("listen.user.qr_code_scan_v2");

    static {
        new ConfigKey("listen.user.qrcodescan_family_rule");
        w = new ConfigKey("listen.user.get_userinfo_qrcode_v2");
        x = new ConfigKey("listen.utilmodule.url.networkdetect");
        y = new ConfigKey("listen.timeoutparam.loading_change_color");
        z = new ConfigKey("listen.thresholdparam.newsong_user");
        A = new ConfigKey("listen.sampleparam.codeless_track");
        B = new ConfigKey("listen.switchparam.feedback_maxreport_count");
        C = new ConfigKey("listen.switchparam.xlogmin_allowreport_sdk");
        D = new ConfigKey("listen.switchparam.track_writepageid");
        E = new ConfigKey("listen.switchparam.enable_xtc_newpicpage");
        F = new ConfigKey("listen.switchparam.event_tracking_sys44");
        G = new ConfigKey("listen.otherparam.event_tracking_h5_blacklist");
        H = new ConfigKey("listen.switchparam.select_bi_data_send_channel");
        I = new ConfigKey("listen.switchparam.event_tracking_h5_report");
        J = new ConfigKey("listen.switchparam.event_tracking_only_wifi_net");
        new ConfigKey("listen.rankmodule.url.newsong_feed_v2");
        K = new ConfigKey("listen.rankmodule.url.https_newsong_feed_v2");
        L = new ConfigKey("listen.switchparam.newsong_encoding");
        M = new ConfigKey("young.tmeab.config_pagesize");
        N = new ConfigKey("young.config.tme_ab");
        O = new ConfigKey("listen.switchparam.diff_platform_config_textsize");
        P = new ConfigKey("listen.switchparam.hauwei_moble_network_showdialog");
        Q = new ConfigKey("listen.switchparam.moble_loss_focus_play");
        R = new ConfigKey("listen.switchparam.listen_login_timeout_time");
        S = new ConfigKey("listen.historycloud.play_song_duration");
        T = new ConfigKey("listen.historycloud.play_song_maxcount");
        U = new ConfigKey("listen.historycloud.playsong_max_chunk");
        V = new ConfigKey("listen.switchparam.login_timeout_switch");
        new ConfigKey("listen.switchparam.pass_recommend_args");
        new ConfigKey("listen.rankmodule.url.newsong");
        W = new ConfigKey("listen.switchparam.pay_v2_master_switch");
        X = new ConfigKey("listen.storagemodule.url.ugctracker");
        Y = new ConfigKey("listen.storagemodule.tracker.url_v3");
        Z = new ConfigKey("listen.storagemodule.tracker.url_v3_https");
        a0 = new ConfigKey("listen.utilmodule.youth.rank_song");
        b0 = new ConfigKey("listen.utilmodule.family_rank_song");
        c0 = new ConfigKey("listen.usermodule.update.userinfo_https");
        new ConfigKey("listen.usermodule.update.userinfo.errorCode_close");
        d0 = new ConfigKey("listen.switchparam.download_onlyvip_canDownload");
        e0 = new ConfigKey("listen.switchparam.openring_onlyvip_canSetRing");
        f0 = new ConfigKey("listen.switchparam.toast_report_stack_new_enable");
        g0 = new ConfigKey("listen.switchparam.huawei_keyboard_enable");
        h0 = new ConfigKey("listen.switchparam.toast_report_no_stack_enable");
        i0 = new ConfigKey("listen.switchparam.xtc_toast_show_enable");
        j0 = new ConfigKey("listen.switchparam.api_success_controller");
        k0 = new ConfigKey("listen.switchparam.pic_apmswitch_enable");
        l0 = new ConfigKey("listen.switchparam.login_report_stack_enable");
        m0 = new ConfigKey("listen.switchparam.picreport_stack_enable");
        n0 = new ConfigKey("listen.switchparam.feedback_stack_enable");
        o0 = new ConfigKey("listen.switchparam.search_report_stack_enable");
        p0 = new ConfigKey("listen.switchparam.fav_report_stack_enable");
        q0 = new ConfigKey("listen.switchparam.report_grade_enable");
        r0 = new ConfigKey("listen.switchparam.ring_report_enable");
        s0 = new ConfigKey("listen.switchparam.rcmpage_report_enable");
        t0 = new ConfigKey("listen.switchparam.rcmpage_forceOffset_enable");
        u0 = new ConfigKey("listen.switchparam.paypage_report_enable");
        v0 = new ConfigKey("listen.switchparam.kadun_report_enable");
        w0 = new ConfigKey("listen.switchparam.autopause_report_enable");
        x0 = new ConfigKey("listen.switchparam.autopause_report2_enable");
        y0 = new ConfigKey("listen.switchparam.fav_sysreport_enable");
        z0 = new ConfigKey("listen.utilmodule.url.uploadimg_v3");
        A0 = new ConfigKey("listen.wallet.url.default");
        B0 = new ConfigKey("listen.mediastore.url.default_https");
        C0 = new ConfigKey("listen.common.bss.upload_get_auth");
        D0 = new ConfigKey("listen.searchmodule.complex.song");
        E0 = new ConfigKey("listen.otherparam.personal_fm_report_profile");
        F0 = new ConfigKey("listen.app.url.shorturl");
        G0 = new ConfigKey("watch.switch.enable_login_shorth5");
        H0 = new ConfigKey("watch.switch.enable_login_shorthicon");
        I0 = new ConfigKey("watch.switch.enable_other_shorth5");
        J0 = new ConfigKey("watch.switch.show_phone_statusper");
        K0 = new ConfigKey("watch.switch.show_huawei_hegui");
        L0 = new ConfigKey("watch.switch.grade_rank_option");
        M0 = new ConfigKey("listen.recommendmodule.url.personal");
        N0 = new ConfigKey("listen.recommendmodule.url.personal_v2");
        new ConfigKey("listen.swithparam.url.personal_use_v1");
        O0 = new ConfigKey("listen.otherparam.url.v2_cmd_switch_enable");
        P0 = new ConfigKey("listen.switchparam.changhong_widgetnotifiy_enable");
        Q0 = new ConfigKey("listen.switchparam.filter_localcancel_error");
        R0 = new ConfigKey("listen.fm.personal.report_history");
        S0 = new ConfigKey("listen.switchparam.persnfm_act_passive_action");
        T0 = new ConfigKey("listen.otherparam.personal_fm_default_robot");
        U0 = new ConfigKey("listen.song.related.audio_album");
        new ConfigKey("listen.fm.personal.report_repeated");
        new ConfigKey("listen.image.url.album_singer_cdn");
        V0 = new ConfigKey("listen.image.url.album_singer_cdnhttps");
        W0 = new ConfigKey("listen.lyricmodule.url.download_https");
        X0 = new ConfigKey("listen.lyricmodule.url.search_v1");
        Y0 = new ConfigKey("young.channel.decor_get_account_stat_watch_v4");
        Z0 = new ConfigKey("young.activity.new_user_send_vip_open_v2");
        a1 = new ConfigKey("young.channel.decor_user_visit_report");
        b1 = new ConfigKey("listen.cloudlistmodule.url.default");
        c1 = new ConfigKey("listen.cloudlistmodule.url.mobile");
        d1 = new ConfigKey("listen.cloudlistmodule.url.get_version");
        e1 = new ConfigKey("listen.cloudlistmodule.url.get_list_all_file_v3");
        f1 = new ConfigKey("listen.albummodule.album_audio_https");
        g1 = new ConfigKey("listen.cloudlistmodule.url.get_all_list_v2");
        h1 = new ConfigKey("listen.cloudlistmodule.url.get_other_all_list");
        i1 = new ConfigKey("listen.utilmodule.suggestion.add");
        j1 = new ConfigKey("listen.cloudlistmodule.url.add_song");
        k1 = new ConfigKey("listen.cloudlistmodule.url.delete_songs");
        l1 = new ConfigKey("fav.longaudio.filter_enable");
        m1 = new ConfigKey("search.longaudio.filter");
        n1 = new ConfigKey("watch.newer.vip_tips");
        o1 = new ConfigKey("watch.iot.qrcode");
        p1 = new ConfigKey("watch.iot.query_event");
        q1 = new ConfigKey("listen.usermodule.url.send_mobile_code_v8");
        new ConfigKey("listen.fingerprint.url.music_trackid");
        new ConfigKey("listen.fingerprint.url.postpcm");
        new ConfigKey("listen.fingerprint.url.stoprequest_signature");
        new ConfigKey("listen.switchparam.identify_request_lever2");
        r1 = new ConfigKey("listen.switchparam.player_log");
        new ConfigKey("listen.fingerprint.url.music_trackid_signature");
        new ConfigKey("listen.switchparam.music_request_finprint_percent");
        new ConfigKey("listen.fingerprint.url.stophumrequest_signature");
        new ConfigKey("listen.fingerprint.url.guesshumphson_signature");
        new ConfigKey("listen.otherparam.audio_identify_algorithm_sample");
        new ConfigKey("listen.fingerprint.url.music_fc_signature");
        new ConfigKey("listen.switchparam.music_request_fc");
        new ConfigKey("listen.switchparam.music_request_fc_percent");
        new ConfigKey("listen.fingerprint.url.guess_sing_song_signature");
        new ConfigKey("listen.switchparam.cantata_recognize");
        new ConfigKey("listen.fingerprint.url.guesshumphsong");
        new ConfigKey("listen.fingerprint.url.posthumpcm");
        new ConfigKey("listen.fingerprint.param_include_unpublish");
        s1 = new ConfigKey("listen.search.content.regex_filter");
        t1 = new ConfigKey("listen.search.content.fuzzy_filter");
        u1 = new ConfigKey("listen.search.content.accurate_filter");
        v1 = new ConfigKey("listen.search.content.force_ignore_list");
        w1 = new ConfigKey("listen.search.content.singer_accurate_filter");
        x1 = new ConfigKey("listen.search.content.song_id_filter");
        y1 = new ConfigKey("listen.nickname.content.errorcode_filter");
        z1 = new ConfigKey("watch.switch.channels_fav_long_audio_filter");
        A1 = new ConfigKey("watch.content.fav_fuzzy_filter_keyword");
        B1 = new ConfigKey("watch.content.fav_accurate_filter_keyword");
        C1 = new ConfigKey("watch.switch.filter_module_illegal_song_v2");
        D1 = new ConfigKey("watch.switch.filter_song_tip");
        E1 = new ConfigKey("watch.switch.refrash_voice_cmd_time");
        F1 = new ConfigKey("listen.switchparam.lyric_transfer_language");
        G1 = new ConfigKey("watch.content.search_song_type");
        H1 = new ConfigKey("watch.switch.audio_identify_entry");
        I1 = new ConfigKey("watch.switch.show_guess_you_like");
        J1 = new ConfigKey("watch.switch.show_main_song_list");
        K1 = new ConfigKey("watch.switch.show_fav_entry");
        L1 = new ConfigKey("watch.switch.show_young_recommend");
        M1 = new ConfigKey("watch.switch.clear_ring_empty");
        N1 = new ConfigKey("watch.content.recommend_zone_home");
        O1 = new ConfigKey("watch.content.recommend_music_sheet");
        P1 = new ConfigKey("watch.search.local_forbidden_keywords");
        Q1 = new ConfigKey("watch.search.local_add_fuzzy_keywords");
        R1 = new ConfigKey("watch.search.local_add_accurate_keywords");
        S1 = new ConfigKey("watch.url.ring_get_res_privilege");
        T1 = new ConfigKey("watch.url.audio_climax");
        U1 = new ConfigKey("watch.url.get_official_img");
        V1 = new ConfigKey("watch.content.ringtone_disable_list");
        W1 = new ConfigKey("listen.sample.fire_eye_samples");
        X1 = new ConfigKey("watch.switch.max_forceupdatesong_list");
        Y1 = new ConfigKey("watch.content.newpage_disable_list");
        Z1 = new ConfigKey("watch.content.hide_feedback_entry");
        a2 = new ConfigKey("watch.content.hide_frist_network_entry");
        new ConfigKey("watch.content.userid_show_network_network_entry");
        b2 = new ConfigKey("watch.content.hook_vip_tip");
        c2 = new ConfigKey("watch.content.custom_vip_tip");
        d2 = new ConfigKey("watch.content.hook_vip_tip_words");
        e2 = new ConfigKey("watch.content.permission_custom_cammera_tip");
        f2 = new ConfigKey("watch.switch.uploadimg_hide_feedback");
        g2 = new ConfigKey("watch.content.permission_custom_album_tip");
        h2 = new ConfigKey("watch.content.show_vip_entry");
        i2 = new ConfigKey("watch.content.show_vip_renewal_button");
        j2 = new ConfigKey("watch.content.vip_payment_service_wx");
        k2 = new ConfigKey("watch.content.login_force_show_2tab");
        l2 = new ConfigKey("watch.content.login_new_page");
        m2 = new ConfigKey("watch.vip.query_product");
        n2 = new ConfigKey("watch.vip.create_order");
        o2 = new ConfigKey("watch.vip.query_order");
        p2 = new ConfigKey("watch.vip.buy_time_strategy");
        q2 = new ConfigKey("watch.vip.create_order_common");
        r2 = new ConfigKey("watch.vip.pay_qr_code_expire_seconds");
        s2 = new ConfigKey("watch.vip.vip_buy_risk_txt");
        t2 = new ConfigKey("listen.usermodule.url.getvipinfo");
        u2 = new ConfigKey("listen.vip8.user.vipinfo");
        v2 = new ConfigKey("watch.switch.radio_def_cover");
        w2 = new ConfigKey("watch.device.low_device_cpu_core");
        x2 = new ConfigKey("watch.device.low_device_memory");
        y2 = new ConfigKey("watch.switch.enable_textview_runlimit_config");
        z2 = new ConfigKey("watch.switch.addfav_error_config");
        A2 = new ConfigKey("watch.switch.enable_ringapm_report_config");
        B2 = new ConfigKey("watch.switch.enable_startapp_time_config");
        C2 = new ConfigKey("watch.content.rank_page_size");
        D2 = new ConfigKey("watch.url.is_disable_connection");
        E2 = new ConfigKey("watch.switch.enable_appicon_show_config");
        F2 = new ConfigKey("watch.switch.enable_xtc_voice_config");
        G2 = new ConfigKey("watch.switch.xtc_enablevoice_version");
        H2 = new ConfigKey("watch.switch.xtc_enablevoice_mod");
        I2 = new ConfigKey("watch.switch.hide_soft_jxw_keyboard_config");
        J2 = new ConfigKey("watch.switch.voice_force_stop_service");
        K2 = new ConfigKey("watch.switch.enable_seach_anim_config");
        L2 = new ConfigKey("watch.content.record_number_url");
        M2 = new ConfigKey("watch.content.record_number_text");
        N2 = new ConfigKey("watch.basic.read_device_id_origin");
        O2 = new ConfigKey("watch.compat.screen_corner_list");
        P2 = new ConfigKey("watch.switch.enable_hardware_accelerated");
        Q2 = new ConfigKey("watch.url.kugou_scan_login_h5");
        R2 = new ConfigKey("watch.switch.vip_page_fordownloadorRing");
        S2 = new ConfigKey("watch.url.xtc_twocode_scan_login_h5");
        T2 = new ConfigKey("watch.switch.controller_fav_sync");
        U2 = new ConfigKey("watch.switch.new_uuid_enable");
        V2 = new ConfigKey("watch.usermodule.risk.r_register_dev");
        W2 = new ConfigKey("watch.statsmodule.deviceid_query");
        X2 = new ConfigKey("watch.switch.enable_product_dynamics_config");
        Y2 = new ConfigKey("watch.vip.promote_config");
        Z2 = new ConfigKey("watch.switch.kill_timeout_crash_config");
        a3 = new ConfigKey("watch.switch.catch_timeout_crash_config");
        b3 = new ConfigKey("watch.vip.promote_config_expire_duration");
        c3 = new ConfigKey("watch.content.com_activity");
        d3 = new ConfigKey("watch.share.illegal_song_tip");
        e3 = new ConfigKey("watch.url.upload_history_config");
        f3 = new ConfigKey("watch.url.linglong_system_apkadapter");
        g3 = new ConfigKey("watch.switch.upload_history_enable");
        h3 = new ConfigKey("watch.url.family_getstatus_controller");
        i3 = new ConfigKey("watch.switch.family_controller_enable");
        j3 = new ConfigKey("watch.switch.family_controller_timefrist");
        k3 = new ConfigKey("watch.url.getlimit_song_config");
        l3 = new ConfigKey("watch.switch.family_controller_timesecond");
        m3 = new ConfigKey("watch.url.family_url_age");
        n3 = new ConfigKey("watch.url.family_url_bind");
        o3 = new ConfigKey("watch.switch.touxinagnew_choose_enable");
        p3 = new ConfigKey("watch.content.play_error_tip");
        q3 = new ConfigKey("watch.content.login_guide_ctrl");
        r3 = new ConfigKey("watch.fav.list_load_optimize");
        s3 = new ConfigKey("watch.switch.enable_song_privilege");
        new ConfigKey("watch.switch.load_queue_optimize");
        new ConfigKey("watch.fav.list_load_attime_optimize");
        t3 = new ConfigKey("watch.fav.list_adapter0num_optimize");
        u3 = new ConfigKey("watch.fav.list_deleteoradd_optimize");
        v3 = new ConfigKey("watch.fav.list_maxreloadCount_optimize");
        w3 = new ConfigKey("watch.fav.list_lostsong_optimize");
        x3 = new ConfigKey("watch.fav.list_apierror_optimize");
        y3 = new ConfigKey("watch.fav.list_forcereload_optimize");
        z3 = new ConfigKey("watch.fav.list_maxsongnum_optimize");
        A3 = new ConfigKey("watch.fav.iconudpate_show_enable");
        B3 = new ConfigKey("watch.fav.list_force_updatechargecount");
        C3 = new ConfigKey("watch.fav.list_force_toastclickcount");
        D3 = new ConfigKey("watch.switch.anr_fix_optimize");
        E3 = new ConfigKey("watch.url.song_report");
        F3 = new ConfigKey("watch.switch.fav_apierror_time");
        G3 = new ConfigKey("watch.switch.jxw_delay_force_killapp");
        H3 = new ConfigKey("watch.switch.force_killapp_delay_time");
        I3 = new ConfigKey("watch.switch.oldfav_option_enable");
        J3 = new ConfigKey("watch.switch.fav_nomixtoast_enable");
        K3 = new ConfigKey("watch.switch.enable_check_position");
        L3 = new ConfigKey("watch.switch.crashfix_mediaservice_enable");
        M3 = new ConfigKey("watch.fav.list_adapternumerror_optimize");
        N3 = new ConfigKey("watch.switch.option_optimize_enable");
        O3 = new ConfigKey("watch.switch.xlog_option_enable");
        P3 = new ConfigKey("watch.switch.xlog_maxsizewrite_enable");
        Q3 = new ConfigKey("watch.switch.xlog_forceuploadbyuserid_enable");
        R3 = new ConfigKey("watch.switch.maxupload_xlogfile_size");
        new ConfigKey("watch.fps.monitor_switch");
        S3 = new ConfigKey("watch.fps.warn_threshold");
        T3 = new ConfigKey("watch.content.fav_sync_thread_count");
        U3 = new ConfigKey("watch.switch.res_privilege_cache");
        V3 = new ConfigKey("watch.content.all_song_play_limit");
        W3 = new ConfigKey("watch.switch.song_listen_trans");
        X3 = new ConfigKey("watch.switch.filter_vip_nooffset_song");
        Y3 = new ConfigKey("watch.switch.rcm_vip_adapter_offset");
        Z3 = new ConfigKey("watch.switch.enable_memory_report");
        a4 = new ConfigKey("watch.switch.enable_memory_tips");
        b4 = new ConfigKey("watch.switch.enable_cartoon_tips");
        new ConfigKey("watch.switch.enable_vippage_playball");
        c4 = new ConfigKey("watch.fps.new_monitor_switch");
        d4 = new ConfigKey("watch.switch.enable_network_report");
        e4 = new ConfigKey("watch.switch.enable_common_network_report");
        f4 = new ConfigKey("watch.switch.enable_exception_report");
        g4 = new ConfigKey("watch.switch.enable_synbi_report");
        h4 = new ConfigKey("watch.switch.get_res_privilege_userinfo");
        i4 = new ConfigKey("watch.switch.toast_context_change");
        j4 = new ConfigKey("watch.switch.enable_refresh_queue");
        k4 = new ConfigKey("watch.switch.enable_refresh_queue_boot");
        new ConfigKey("watch.switch.repair_player_oom");
        l4 = new ConfigKey("watch.switch.enable_force_killapp");
        m4 = new ConfigKey("watch.switch.enable_Bluetooth_ctl");
        n4 = new ConfigKey("listen.musicstore.music.goods_list_version_v2");
        o4 = new ConfigKey("listen.user_assert.maxcount");
        p4 = new ConfigKey("listen.switchparam.fee_limited_free");
        q4 = new ConfigKey("listen.switchparam.watch_config");
        r4 = new ConfigKey("watch.switch.play_cache_error_retry");
    }
}
